server:
  port: 3002


spring:
  cloud:
    stream:
      function:
        bindings:
          domainProcessor-in-0:
            destination: web-domains
          domainProcessor-out-0:
            destination: active.web-domains
      kafka:
        bindings:
          domainProcessor-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          domainProcessor-out-0:
            consumer:
              configuration:
                value:
                  serializer: org.springframework.kafka.support.serializer.JsonSerializer
        binder:
          brokers:
            - localhost:9091
            - localhost:9092