server:
  port: 3003

spring:
  cloud:
    stream:
      function:
        bindings:
          domainProcessor-in-0:
            destination: web-domains
      kafka:
        bindings:
          domainProcessor-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        binder:
          brokers:
            - localhost:9091
            - localhost:9092